name: Terraform Workflow

on:
  pull_request:
    branches:
      - main  

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.7  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Fmt
        run: terraform fmt -recursive -check

  validate:
    runs-on: ubuntu-latest
    needs: fmt  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.7  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate